### ISSUE TITLE
Vaadin 7.1.0 support

### ISSUE THREAD

**Issue by ledbruno** [jounik/CSSInject#2]
We are facing problems to use VAADIN 7.1.0, Is there any forecast about Vaadin 7.1.0 support?

It seems that CSS Inject project has some fixed dependencie versions. Can we change that for VAADIN 7.1.0 or make it flexible so it uses my project´s Vaadin version?

Thanks!

**Comment by jounik** [comment]
Please re-open if you still have problems with the latest Vaadin Framework version.
